# Generated by Django 5.2.17 on 2026-10-02 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=100)),
                ('titulo_obtenido', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_idioma', models.CharField(max_length=100)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.nivel')),
            ],
        ),
    ]
